### PR TITLE
Updated CI/CD workflows, more automation & more.

### PR DESCRIPTION
**Pull request by hitblast**
### Things changed:

- [x] The codebase has been linted using the [flake8](https://flake8.pycqa.org) linter.
- [x] Fixed build workflows running on every push (now limited to release and manual dispatches only).
- [x] Added a new GitHub Actions workflow for automating the linting process.
- [x] Added a new GitHub Actions workflow for PyPI releases (https://github.com/TechWiz-3/happy-jar-cli/issues/3)
- [x] Added configuration files for Visual Studio Code which correlate to the linter.
- [x] Last but not the least, prettified the root markdown (README.md) a little :D

### CODE REVIEW

**Comment by TechWiz-3** [comment]
Weee, great work 🔥 

A few things:
1. Remove the `<br>` tags in README for more compact look
2. Put the `cron` back in `build.yml`. This is because after 3 months, artifacts expire, so if no new updates are made, the artifacts will expire
3. Question: in `pypi-releasse` the binaries being uploaded are `.whl` files, right?

**Comment by hitblast** [comment]
@TechWiz-3 Thanks for the review!

1. Doing it.
2. Doing it too.
3. Both the wheels and the compressed source files (`.whl`. and `.tar.gz`) are uploaded.

**Comment by hitblast** [comment]
Done! @TechWiz-3 Feel free to review when you're free :D

**Comment by TechWiz-3** [comment]
Neat 👌 thank you

**Pull request merged**
