### PR TITLE
Refactor the codebase

### PR DESCRIPTION
**Pull request by diwash007**
Refactored the codebase
Added docstrings
Fixed Typos

### CODE REVIEW

**Comment by TechWiz-3** [comment]
Thank you for this, I definitely like the setup you've made here.
Currently there are two things from stopping me from merging this immediately
1. a lot of PRs came in directly after this using the setup in the main branch so refactoring should be done after those PRs are merged
2. this setup means that testing locally will be a headache because running `main.py` will keep importing the pip installed repo packages rather than the locally tested/edited packages (I believe this issue can be solved neatly with `poetry`)

I will be working on these two issues very soon (as soon as I finish an exam I will be taking tomorrow). Once those issues are solved I would love implement this refactoring form 👍

**Comment by fr4nkln11** [comment]
Hi, I also like the work you've done here, should I wait until this is merged or should I just add my feature to the regular codebase.
I would like to get working on it as soon as possible.

**Comment by TechWiz-3** [comment]
> Hi, I also like the work you've done here, should I wait until this is merged or should I just add my feature to the regular codebase. I would like to get working on it as soon as possible.

Thank you for this question, just use the main codebase for now. We'll talk about refactoring it later

**Comment by TechWiz-3** [comment]
Alright, a development environment has been setup using poetry (please see `README.md` for more details), if you're still up for this then go ahead 👍

**Pull request closed without merging**
