### PR TITLE
NEW: colored output and entry display formatting

### LINKED ISSUE #13: Add colours to CLI ouput
I would like to modify the codebase by adding color to CLI prompts, like error messages and successful entry prompts.
I think it would give the CLI  a nice look to it.

I would like to personally take on this issue, its in fact my first issue on github 😄

### PR DESCRIPTION
**Pull request by fr4nkln11**
Same as my previous PR but using Textualize/rich, 
This new PR has more additions than the last, I used `rich.markdown` for highlighting commands, used `rich.theme` to make it easier to modify color styles later, and I added a header and footer format when displaying entries.
Also I added a `--nocolor` option which returns all color and style settings to default when displaying entries, as per your request.

Please feel free to make changes to this after merging, especially with the color choices, you can change them to whatever you think seems right, the current setting looks good on both light and dark terminals.

Fix #13

### CODE REVIEW

**Comment by TechWiz-3** [comment]
WOW, you have gone above and beyond for this one 🔥 

Could you please change the entry default to regular text, rather than bold. It can get a little much on the eyes.

Otherwise, I like this PR very much, in the future we can even have more options or a config file to format the output to the user's liking 💪

**Comment by TechWiz-3** [comment]
All good, I've done it myself

**Comment by fr4nkln11** [comment]
sorry I'm replying late,
Thanks for accepting the PR and I'm glad you were able to add your own touch to it,
I think my next contribution will be modifying the docs i.e the README.md, the docstrings and CLI help.

**Comment by TechWiz-3** [comment]
Yesss that would be great!

**Pull request merged**
