### PR TITLE
Using `json` for data storage

### LINKED ISSUE #30: Using a different medium to store logs apart from `txt`
I think using json to store entries could open up opportunities for new features,
Instead of storing the entry as a string in a .txt file, we could try breaking up the string to get useful information that we can use to group entries.
Example:
We could be able to group entries by `month`, `week`, `year` etc
Plus, it should be easier to use json data in the program.
We could even try grouping by tags
That should be cool right.

Please assign me to this issue

### PR DESCRIPTION
**Pull request by fr4nkln11**
Major changes in this PR
## modifying `write_file()`:
So, basically I have modified the `write_file()` function to support json as the file to write to, an additional feature here is the ability to convert data from the already existing `.txt` data file to objects for the new `.json` file, with this, users won't lose their data when they upgrade to the new version.

## modifying `read_file()`:
I modified this function to extract data from the data file based on the conditionals given, and pass the extract data as a dictionary to `display_entry()`.

## modifying `display_entry()`:
I modified this function to use the already extracted json data without the need for extra text processing techniques (I think this should help improve performance a bit)

## other modifications
I made other modifications across the entire file, like fixing output for `count` and `tags`, adding style to tags in `display_entry()`, improving a few algorithms, removing redundant steps etc

Just as i promised, the CLI continues to work as intended, the change in data file format should not even be noticeable to the user except for slightly performance improvements (that is if there are any, I didn't carry out any performance tests)

I noticed my branch was 1 commit behind, but I dont think that should haffect this merge, because the change made in that commit was affecting a section of the code I removed in mine, feel free to check the code and tell me what you think.

Fixes #30

### CODE REVIEW

**Comment by fr4nkln11** [comment]
So how is it? Have you tested it yet?

**Comment by TechWiz-3** [comment]
Brother you have gone above and beyond for this one.

Tests are working fine, right now, I'm just going through the code and digesting things.

**Comment by fr4nkln11** [comment]
Great 👍

**Comment by TechWiz-3** [comment]
Thanks a lot, this was really great work, and I love how included migrating the existing `.txt` happy jar to the `.json` happy jar.

I reckon you should put these sorts of PRs in your resume when applying for tech jobs 🔥

**Pull request merged**
