### PR TITLE
📦 NEW: get tags command

### LINKED ISSUE #34: Add new command `happy get tags` to view list of all tags used yet
As discussed in #28:

> A future enhancement can be adding support for a new command like happy tags which lists all the tags used so far. This command can be a nice way to 1st check all tags used so far and then view entries of a certain tag from that list.

I'd like to add this command now that the basic tagging feature is ready!

### PR DESCRIPTION
**Pull request by N-Shar-ma**
Fixes: #34 

Screenshot of using the new command in combination with the feature added in #31:
image

### CODE REVIEW

**Comment by fr4nkln11** [comment]
@N-Shar-ma I have one question, how easy was it for you to add the new commands, with `argparse`, and do you think it would be easier with `click`?

**Comment by N-Shar-ma** [comment]
@fr4nkln11 Not really familiar with click, but as someone new to working with CLIs in python, the current set up wasn't too hard to understand and follow by observing how the other commands work. Some googling to confirm how certain methods and arguments work was needed, but that's natural.

The only part that seemed clunky to me was checking the presence of a certain argument using string equality (like `args.all == "tag"`) but I am not sure if this is related to the library, or if simply refactoring is needed. 

I did look up click, and it seems less wordy, cleaner and modern (uses decorators), but am not sure if that is worth having a new dependency.

Hope this helps!

**Comment by fr4nkln11** [comment]
Great, thanks for your input.

**Comment by TechWiz-3** [comment]
Thanks a lot, this is great work 🙏 

I have included a small commit that changes the setup and logic of `tags` and `count` a little more to my liking.

Tags will be spaced out if the `flowers` option is used to maintain clarity between the printed flowers

Screen Shot 2022-10-23 at 10 51 48 am
---
Screen Shot 2022-10-23 at 10 51 08 am
---
Screen Shot 2022-10-23 at 10 50 20 am
---
Screen Shot 2022-10-23 at 10 50 03 am
---
Screen Shot 2022-10-23 at 10 49 49 am
---
Screen Shot 2022-10-23 at 10 49 44 am

**Pull request merged**
