### PR TITLE
Add new commands `happy get count`

### PR DESCRIPTION
**Pull request by TanmayPatil105**
Added a new command `count` which displays how many times we were happy on each day

Screenshot 

Screenshot from 2022-10-02 23-25-33

### CODE REVIEW

**Comment by TechWiz-3** [comment]
This is a great addition, thank you very much. Currently I need to make some changes to the repo before merging any new PRs and atm I just don't have the time as I'm preparing for an exam tomorrow 😅. Hopefully in a few days I'll be able to merge this 👍

**Comment by TechWiz-3** [comment]
Please fix the flake8 warnings, then I will merge 👍

**Comment by TechWiz-3** [comment]
It's ok, I've fixed them myself

**Comment by TanmayPatil105** [comment]
Thanks 😃

**Pull request merged**
